#!/bin/bash
InputFile=$1  #Shell input file (med file)
OutputFileName=${InputFile:0:-4}  #Remove the file format (.med)
gmsh $1 -3 -format "msh2" -v 0  #Create msh file with Gmsh 
dolfin-convert "$OutputFileName.msh" "$OutputFileName.xml"  #Convert msh file to final xml files
